server:
  port: 8086

spring:
  application:
    name: weather-service

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8085/realms/agrivision

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


weather:
  api:
    key: 1b8abe8b5165b673a8c34e04c5494efd
    url: https://api.openweathermap.org/data/2.5/weather
