server:
  port: 8081  # ou le port que tu utilises r√©ellement pour plant-service

spring:
  application:
    name: plant-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/agrivision  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka